export enum ForAge {
  OVER_NINE = "OVER_NINE",
  OVER_ONE_TO_TWO = "OVER_ONE_TO_TWO",
  SEVEN_TO_TWELVE_MONTH = "SEVEN_TO_TWELVE_MONTH",
  SIX_TO_EIGHT = "SIX_TO_EIGHT",
  THREE_TO_FIVE = "THREE_TO_FIVE",
  ZERO_TO_SIX_MONTH = "ZERO_TO_SIX_MONTH",
}
